/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CommonContent: typeof import('./src/components/layout/CommonContent.vue')['default']
    CommonFooter: typeof import('./src/components/layout/CommonFooter.vue')['default']
    CommonHeader: typeof import('./src/components/layout/CommonHeader.vue')['default']
    CommonLayout: typeof import('./src/components/layout/CommonLayout.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseMessage: typeof import('./src/components/UseMessage.vue')['default']
    UsePiniaDemo: typeof import('./src/components/UsePiniaDemo.vue')['default']
  }
}
